- name: Установка Process Explorer на Windows

  hosts: windows

  tasks:

    - name: Скачивание установщика
      win_get_url:
        url: "https://download.sysinternals.com/files/ProcessExplorer.zip"
        dest: "C:\\Temp\\ProcessExplorer.zip"

    - name: Распаковка архива
      win_unzip:
        src: "C:\\Temp\\ProcessExplorer.zip"
        dest: "C:\\Temp"
